### ISSUE TITLE
Missing IronPython.Wpf.dll ?

### ISSUE THREAD

**Issue by Cyril-Pop** [DynamoDS/DSIronPython3#2]
## Dynamo version

Dynamo Revit 2.16 

## Operating system

Win 11

## What did you expect to see?

No Error loading wpf IronPython module

## What did you see instead?

Error, IronPython.Wpf.dll seem not include in DSIronPython3 package
```
Node Name: Python Script
Package: Core.Scripting
Dynamo Version: 2.16.1.2727
Host: Dynamo Revit
Messages: PythonEvaluator.Evaluate l'opération a échoué.
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "<string>", line 540, in _check_name_wrapper
  File "C:\Users\sneep\AppData\Roaming\Dynamo\Dynamo Revit\2.16\packages\DynamoIronPython3\extra\lib\wpf.py", line 14, in <module>
  File "<string>", line 1565, in load_module
  File "<string>", line 597, in _load_module_shim
  File "<string>", line 1208, in load
  File "<string>", line 1188, in _load_unlocked
  File "<string>", line 1117, in _exec
  File "<string>", line 1459, in exec_module
  File "<string>", line 322, in _call_with_frames_removed
ImportError: No module named '_wpf'
State: Warning
```
![image](https://user-images.githubusercontent.com/53660624/236803102-ffd53285-230d-4194-9277-4b34d19035fd.png)

## code to reproduce

```
import clr	
import sys
import System

clr.AddReference("IronPython.Wpf")
clr.AddReference('System.Core')
clr.AddReference('System.Xml')
clr.AddReference('PresentationCore')
clr.AddReference('PresentationFramework')

from System.IO import StringReader
from System.Windows.Markup import XamlReader, XamlWriter
from System.Windows import Window, Application

from System import Uri
from System.Windows.Media.Imaging import BitmapImage

import wpf
```

**Comment by mjkkirschner** [comment]
so this should be fixed if we merge this:
https://github.com/DynamoDS/DSIronPython3/pull/4

net6 targets include wpf, net std 2 cannot.

Can I ask what are the use cases for the IronPython.Wpf module?

**Comment by Cyril-Pop** [comment]
Hi,
IronPython.Wpf module is necessary when users use WPF and/or MVVM with IronPython (instead of Win form)

here some examples on forum


https://forum.dynamobim.com/t/wpf-form-datagrid-with-comboboxes-inside/86924/4?u=c.poupin

https://forum.dynamobim.com/t/wpf-progressbar/83976/2?u=c.poupin

https://forum.dynamobim.com/t/wpf-application-crashes-dynamo/81469

**Comment by Cyril-Pop** [comment]
This module loads the XAML from the specified XmlReader and returns the deserialized object with the xaml properties, events, etc... (ipy objects)

more info here

https://github.com/IronLanguages/ironpython3/blob/master/Src/IronPython.Wpf/_wpf.cs

**Comment by Cyril-Pop** [comment]
@mjkkirschner  
if **wpf** module integration is a problem for Net 7 (or higher)
There is still a workaround with `LogicalTreeHelper` class

I just tested in Revit Preview and it works
![image](https://github.com/DynamoDS/DSIronPython3/assets/53660624/c32da7db-8031-45bb-8e36-ef25c44e6f69)

```
import clr    
import sys
import System
clr.AddReference("System.Xml")
clr.AddReference("PresentationFramework")
clr.AddReference("System.Xml")
clr.AddReference("PresentationCore")
clr.AddReference("System.Windows")
import System
from System.Collections.Generic import List
from System.IO import StringReader
from System.Xml import XmlReader
from System.Windows import LogicalTreeHelper 

from System.Windows.Markup import XamlReader, XamlWriter
from System.Windows import Window, Application

clr.AddReference('System.Data')
from System.Data import *

class MyWindow(Window):

    LAYOUT = '''
    <Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Window2"
        Width="600"
        Height="336">
        <Grid>
            <DataGrid
                Grid.Column="0"
                Grid.Row="0"
                HorizontalAlignment="Stretch"
                VerticalAlignment="Top"
                Margin="17,30,18,0"
                Height="209"
                x:Name="DataGrid" />
            <Button
                Content="OK"
                Grid.Column="0"
                Grid.Row="0"
                HorizontalAlignment="Right"
                VerticalAlignment="Bottom"
                Margin="0,0,20,20"
                Width="96"
                Height="30"
                x:Name="OKButton" />
        </Grid>
    </Window>'''
                
    def __init__(self):
        self._xaml = MyWindow.LAYOUT   
        xr = XmlReader.Create(StringReader(self._xaml))
        self.winLoad = XamlReader.Load(xr)       
        self.winLoad.Title = f"test {sys.implementation.name} : {sys.version}"
        self._datagrid1 = LogicalTreeHelper.FindLogicalNode(self.winLoad, "DataGrid")
        self._button = LogicalTreeHelper.FindLogicalNode(self.winLoad, "OKButton")
        self._button.Click += self.ButtonClose_Click
        #
        self._tableGrpType = DataTable("DetailGroups")
        self._tableGrpType.Columns.Add("Type1\n(2.4)", System.Double)
        self._tableGrpType.Columns.Add("Type2\n(3.6)", System.Double)
        self._tableGrpType.Columns.Add("Type3\n(5)", System.Double)
        self._tableGrpType.Columns.Add('Calculation\n(Type1 * 2.4 + Type2 * 3.6 + Type3 * 5)', 
                                        System.Double, 
                                        "[Type1\n(2.4)] * 2.4 + [Type2\n(3.6)] * 3.6 + [Type3\n(5)] * 5")
        # populate dataTable
        self._tableGrpType.Rows.Add(1, 1, 1)
        self._datagrid1.ItemsSource = self._tableGrpType.DefaultView
            
    def ButtonClose_Click(self, sender, e):
        self.outTable =  self._datagrid1.ItemsSource.ToTable("outTable")
        self.winLoad.Close()
        
def appThread():
    global resultTable
    my_window = MyWindow()
    my_window.winLoad.ShowDialog()
    resultTable =  my_window.outTable
    
resultTable = None
appThread()

valueA = resultTable.Rows[0]["Type1\n(2.4)"] # or resultTable.Rows[0][0]
valueB = resultTable.Rows[0]["Type2\n(3.6)"] # or resultTable.Rows[0][1]
valueC = resultTable.Rows[0]["Type3\n(5)"] # or resultTable.Rows[0][2]
valueResult = resultTable.Rows[0][3] 

OUT = valueA, valueB, valueC, valueResult,
```

**Comment by mjkkirschner** [comment]
Hi @Cyril-Pop I don't think it will be a problem. I have merged that change here but have not been able to publish the package yet.

If you build this repo from source does it work for you locally?

**Comment by Cyril-Pop** [comment]
> If you build this repo from source does it work for you locally?

I'll try by the end of the week, 
_I thought it was in the repository only to report Issues_

**Comment by Cyril-Pop** [comment]
I just tested, it works well :

- ok on DynamoSandBox : Net6.0 
- ok on Revit Preview : Net 7.0

![image](https://github.com/DynamoDS/DSIronPython3/assets/53660624/6674b547-c9c0-4e89-8b34-e04de41f0d54)
